language: python
python:
  - 2.7

env:
  - DJANGO=1.8.14
  - DJANGO=1.10.6
  - DJANGO=1.11.2

install:
  - pip install Django==$DJANGO
  - python setup.py install
  - pip install coverage
  - pip install mock
  - pip install nose

script: coverage run test.py

after_success: bash <(curl -s https://codecov.io/bash)
